FROM alpine:latest
CMD echo "Hello from Alpine"

# The main purpose of a CMD is to provide defaults for an executing container.
# There can only be one CMD instruction in a Dockerfile. If you list more than one CMD then only the last CMD will take effect.