FROM httpd:2.4

EXPOSE 80

# The EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime. You can specify whether the port listens on TCP or UDP, and the default is TCP if the protocol is not specified.

# Below CMD work with the docker run 
# -d = Deatached mode/ run the container in backround
# -P = Publish all exposed ports and map them to high-order ports.
# -p = to publish and map one or more ports